### ISSUE TITLE
Swift port

### ISSUE THREAD

**Issue by airy10** [malmeloo/FindMy.py#11]
In case anyone is interested, I've started a Swift port of this library
Still a lot to do since only the KeyPair and Accessory classes are ported but that's enough to generate to the primary and secondary keys for any date from the original private key and shared secret

[SwiftFindMy](https://github.com/airy10/SwiftFindMy
)

**Comment by malmeloo** [comment]
Cool! I think I will start keeping track of derivative projects in the README. Thanks for sharing this!
