### ISSUE TITLE
Is OfflineFindingScanner supported on Windows?

### ISSUE THREAD

**Issue by darthnithin** [malmeloo/FindMy.py#24]
Is OfflineFindingScanner meant to work on windows?
If so, it doesn't and also it doesn't give a graceful error message
![image](https://github.com/malmeloo/FindMy.py/assets/10778861/fd4c88be-2926-4dd0-b3ab-424b39722d74)

**Comment by darthnithin** [comment]
![image](https://github.com/malmeloo/FindMy.py/assets/10778861/ae3c3dd2-7709-4220-9b2c-e0baef765aec)
makes me think it's not, but it would be great if there was a more relevant error message. Also "platform agnostic" is in the readme which is a little confusing?

**Comment by malmeloo** [comment]
Thanks for reporting this! It should indeed work on Windows, but I haven't actually been able to test that myself. It looks like the library behaves a little differently on Windows compared to Linux/Mac OS, which is causing the issue.

Unfortunately I don't have a lot of time to look into this right now, but I intend to pick development back up very soon and will fix this asap.

**Comment by darthnithin** [comment]
![image](https://github.com/malmeloo/FindMy.py/assets/10778861/fac7c4e5-e549-4091-a0fc-0d59a69164d8)
macos returns this tuple
![image](https://github.com/malmeloo/FindMy.py/assets/10778861/cbe5622f-0f41-4e44-8eb8-136b17dc7a9b)
while windows returns a [BluetoothLEAdvertisementReceivedEventArgs](https://learn.microsoft.com/en-us/uwp/api/windows.devices.bluetooth.advertisement.bluetoothleadvertisementreceivedeventargs?view=winrt-22621)
![image](https://github.com/malmeloo/FindMy.py/assets/10778861/db0dc982-2166-4762-ae14-39b5dcfd3109)
![image](https://github.com/malmeloo/FindMy.py/assets/10778861/5e417229-14db-41b5-9e03-d42658d18547)

**Comment by malmeloo** [comment]
This should now be fixed on main and will be included in the next release which is scheduled for this week. Please let me know if the issue persists.
