### ISSUE TITLE
coroutine 'AppleAccount.close' was never awaited

### ISSUE THREAD

**Issue by hkfuertes** [malmeloo/FindMy.py#59]
Hello, don't know if this is a bug... but sometimes I get this issue:

```bash
/usr/local/lib/python3.11/asyncio/base_events.py:679: RuntimeWarning: coroutine 'AppleAccount.close' was never awaited
  self._ready.clear()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
ERROR:asyncio:Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7845015c8450>
ERROR:asyncio:Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x78450272cec0>, 2831.831099158)]']
connector: <aiohttp.connector.TCPConnector object at 0x7845015f3f50>
ERROR:asyncio:Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7845015cf090>
ERROR:asyncio:Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7845015b81a0>, 2832.221270141)]']
connector: <aiohttp.connector.TCPConnector object at 0x7845015f3a50>
```

Thank you for your work, I'm an android user, and through this I was able to pin point my tags in a Home Assistant map :)

**Comment by malmeloo** [comment]
Can confirm, I run into this issue too sometimes. The sync wrapper attempts to clean up when an account object is gc'd, but for some reason the coroutine is never actually awaited, resulting in that warning. It's harmless, but quite annoying.

I haven't really found a solution to this yet, but thanks for filing an official bug report :-)

**Comment by malmeloo** [comment]
Would you be willing to try #60 to see if it fixes the issue? i.e.:

```bash
pip install git+https://github.com/malmeloo/FindMy.py@fix/coro-never-awaited
```

It's been much more reliable for me, I hope it's a universal solution.

**Comment by hkfuertes** [comment]
It seems to be working... I stressed the program... but no error have been shown...

**Comment by malmeloo** [comment]
Nice to hear! I'll go ahead and merge the change then, new release should be out in a bit.
